export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMONS_TYPES = 'GET_POKEMONS_TYPES';
export const GET_POKEMONS_DETAIL = 'GET_POKEMONS_DETAIL';
export const GET_POKEMON_NAME = 'GET_POKEMON_NAME';
export const POKEMONS_TYPE = 'POKEMONS_TYPE';
export const FILTER_POKEMON = 'FILTER_POKEMON';
export const SEARCH_POKEMON = 'SEARCH_POKEMON';