export const GET_POKEMONS = 'GET_POKEMONS';
export const GET_POKEMONS_TYPES = 'GET_POKEMONS_TYPES';
export const GET_POKEMONS_DETAIL = 'GET_POKEMONS_DETAIL';
export const GET_POKEMON_NAME = 'GET_POKEMON_NAME';
export const SET_POKEMON_DETAIL = 'SET_POKEMON_DETAIL';
